-- =====================================================
-- Migration 019: Widen VARCHAR columns in ifs_personalized_curriculum
-- primary_wound_focus was VARCHAR(50), which is too short for
-- longer wound focus strings generated by the curriculum personalizer.
-- =====================================================

ALTER TABLE ifs_personalized_curriculum
  ALTER COLUMN primary_wound_focus TYPE TEXT,
  ALTER COLUMN difficulty_level TYPE TEXT;
